apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: controller.serviceType
          value: LoadBalancer
        - name: controller.adminUser
          value: "admin"
        - name: controller.adminPassword
          value: "yourpassword"
      chart: jenkinsci/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
